version: "3.9"

services:
  frontend:
    image: felipevipa/proyectods4afrontend:v2
    ports:
      - "80:80"
    restart: always

  backend:
    image: felipevipa/proyectods4abackend:v1
    ports:
      - "5000:5000"

    restart: always
